namespace:
  name: prod
 
image:
  pullPolicy: Always

deployment:
  replicaCount: 5
  resources:
    requests:
      memory: 128Mi
      CPU: 350m
    limits: 
      memory: 256Mi
      CPU: 500m

service:
  port: 7111
